# DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource:
    url: jdbc:mysql://localhost:3306/todo?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: admin

# Hibernate
spring.jpa:
    properties.hibernate.dialect : org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto : update

logging.level.org.hibernate:
    SQL: DEBUG
    type: TRACE

# Mail configuration
spring.mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: todoAppJakov992@gmail.com
    password: Todo992@
    mail.smpt.starttls.enable: true
    mail.smpt.auth: true